name: Demo Mill Problem
on:
  push:
jobs:
  demo-jar-command:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "name=$(./mill showNamed tmp.jar | jq -r '."tmp.jar"')" >> $GITHUB_OUTPUT
        id: get-name
      - run: echo "${{ steps.get-name.outputs.name }}"
  demo-nativeLink-command:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "name=$(./mill showNamed tmp.nativeLink | jq -r '."tmp.nativeLink"')" >> $GITHUB_OUTPUT
        id: get-name
      - run: echo "${{ steps.get-name.outputs.name }}"
