name: Demo Mill Problem
on:
  push:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "bin_name=$(./mill showNamed tmp.nativeLink 2>/dev/null | jq -r '."tmp.nativeLink"')" >> $GITHUB_OUTPUT
        id: get-name
      - run: echo "${{ steps.get-name.outputs.bin_name }}"
