name: Demo Mill Problem
on:
  push:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "jar_name=$(./mill showNamed tmp.jar 2>/dev/null | jq -r '."tmp.jar"')" >> $GITHUB_OUTPUT
        id: get-name
      - run: echo "${{ steps.get-name.outputs.jar_name }}"
